name: Real Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hi
        run: |
          echo "Welcome Sahil!"
          echo "Today is $(date)"
