name: Hello World Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'  # every day at noon UTC
  workflow_dispatch:  # manual trigger button

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from Sahil’s first GitHub Action!"
